apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: cnpg
spec:
  instances: 3
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 16Gi
    storageClass: local-path
