apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.23.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 10m
