apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
      interval: 10m
  values:
    allowLoopDevices: true
