apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 10m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: '1.16.0'
      sourceRef:
        kind: HelmRepository
        name: rook
        namespace: flux-system
      interval: 10m
  values:
    cephClusterSpec:
      storage:
        useAllDevices: false
        devices:
          - name: /dev/loop0
    toolbox:
      enabled: true
