apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  chart:
    spec:
      chart: lldap
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: djjudas21
        namespace: flux-system
  interval: 30m
  values:
    replicaCount: 3
    externalPostgresql:
      enabled: true
      auth:
        host: "postgres-rw.cnpg.svc.cluster.local"
        database: lldap
    lldap:
      baseDN: "dc=internal,dc=rooty,dc=dev"
  valuesFrom:
    - kind: Secret
      name: lldap-postgres
      valuesKey: username
      targetPath: "externalPostgresql.auth.username"
    - kind: Secret
      name: lldap-postgres
      valuesKey: password
      targetPath: "externalPostgresql.auth.password"
    - kind: Secret
      name: lldap-secret
      valuesKey: password
      targetPath: "lldap.ldapUserPass"
    - kind: Secret
      name: lldap-secret
      valuesKey: lldap-jwt-secret
      targetPath: "lldap.jwtSecret"
    - kind: Secret
      name: lldap-secret
      valuesKey: lldap-key-seed
      targetPath: "lldap.keySeed"
