apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: valkey
spec:
  interval: 10m
  chart:
    spec:
      chart: valkey
      version: '2.2.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    global:
      defaultStorageClass: local-path
    auth:
      existingSecret: valkey
      existingSecretPasswordKey: password
    replica:
      replicaCount: 2
    sentinel:
      enabled: true
