apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: op-connect
  namespace: op
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: '1.17.0'
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 10m
  values:
    operator:
      create: true
